<events>
  <event>
    <id>templateType_datagrid1_add_onClick</id>
    <eventType>onClick</eventType>
    <code><![CDATA[this.add();]]></code>
  </event>
  <event>
    <id>templateType_datagrid1_update_onClick</id>
    <eventType>onClick</eventType>
    <code><![CDATA[this.edit();]]></code>
  </event>
  <event>
    <id>templateType_datagrid1_delete_onClick</id>
    <eventType>onClick</eventType>
    <code><![CDATA[this.delete();]]></code>
  </event>
  <event>
    <id>templateType_datagrid1_save_onClick</id>
    <eventType>onClick</eventType>
    <code><![CDATA[this.save();]]></code>
  </event>
  <event>
    <id>templateType_pwpText1_onBlur</id>
    <eventType>onBlur</eventType>
    <parameterType>event</parameterType>
    <code><![CDATA[this.check_name();]]></code>
  </event>
</events>